name: Extract symbols on dependabot updates

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
    if: ${{ github.actor == 'dependabot[bot]' }}
  extract-symbols:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress
      - name: Run extract script
        run: composer run-script extract
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add -A
          git commit -m "Extract symbols after Dependabot update"
          git push
